#!/bin/bash
# set -exuo pipefail

readonly SCRIPT_DIR=$(dirname "$0")
readonly GRADLEW="${SCRIPT_DIR}/gradlew"
readonly GRADLEW_ARGS=$([ -z "$@" ] && echo "" || echo "--args \"$@\"")


pushd "$SCRIPT_DIR"
cargo run -- "$@"
popd